#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*-----------------------------------------------------------------------------------
Robot code for GHS VEX Team G
2018-19 Competiton Season

Team members are Lucas Ritzdorf, Riker Foster, and Lauryn Vornbrock.

In this code, all functions for manually controlled movement are inside the
driverControl task.
-----------------------------------------------------------------------------------*/

// Remote mappings:
// Left stick Y-value:  vexRT[Ch3]
// Right stick Y-value: vexRT[Ch2]

// Standard sleep value (in milliseconds)
// Can be adjusted for responsiveness as needed
const int sleepValue = 20;

task pre_drive() {
	// Pre-driving setup
	// Set servo positions, etc.
}

task autonomous() {
	// Autonomous code
}

task driverControl() {
	// Driver-control code
	motor[leftMotor] = vexRT[Ch3];
	motor[rightMotor] = vexRT[Ch2];
  sleep(sleepValue);
}

task main() {
	startTask(pre_drive);
	startTask(autonomous);
	sleep(15000);
	startTask(driverControl);
	while(true) {
		sleep(1000);
	}
}
